Repository nasa/ow_simulator, pull requests merged in 2020-12, with the labels that each got.

#39 Oceanwater 525 refactor arm services to use moveit based on joint trajectory controller interface
  ow_lander/config/lander.srdf
  ow_lander/launch/spawn.launch
  ow_lander/scripts/activity_deliver_sample.py
  ow_lander/scripts/activity_full_digging_traj.py
  ow_lander/scripts/activity_guarded_move.py
  ow_lander/scripts/path_planning_commander.py
  ow_lander/srv/DeliverSample.srv
  ow_lander/srv/GuardedMove.srv
  ow_lander/srv/Stow.srv
  ow_lander/srv/Unstow.srv
Labels: enhancement, feature

#47 Oceanwater-558 adding grinder fault for arm
  ow_faults/cfg/Faults.cfg
  ow_faults/src/FaultInjector.cpp
Labels: faults injection

#46 Created new pull request template
  pull_request_template.md
Labels: faults injection

#44 Oceanwater 530 enable switching between arm controllers at runtime
  ow_lander/config/fake_controllers.yaml
  ow_lander/config/ros_controllers.yaml
  ow_lander/launch/ros_controllers.launch
  ow_lander/scripts/activity_full_digging_traj.py
  ow_lander/scripts/activity_grind.py
  ow_lander/scripts/path_planning_commander.py
  ow_lander/scripts/utils.py
  ow_lander/srv/DigCircular.srv
  ow_lander/srv/DigLinear.srv
  ow_lander/srv/Grind.srv
Labels: feature

#45 OceanWaters 554 Faults Messaging System
  ow_faults/CMakeLists.txt
  ow_faults/include/ow_faults/FaultInjector.h
  ow_faults/msg/ArmFaults.msg
  ow_faults/msg/SystemFaults.msg
  ow_faults/package.xml
  ow_faults/src/FaultInjector.cpp
Labels: faults injection

#52 Oceanwater 540 factor out ground detection functionality out of trajectory publisher
  ow_lander/msg/GuardedMoveResult.msg
  ow_lander/scripts/activity_deliver_sample.py
  ow_lander/scripts/activity_full_digging_traj.py
  ow_lander/scripts/activity_guarded_move.py
  ow_lander/scripts/ground_detection.py
  ow_lander/scripts/path_planning_commander.py
  ow_lander/scripts/trajectory_async_execution.py
  ow_lander/scripts/trajectory_publisher.py
Labels: enhancement, feature

#53 Rework the README.md
  ow_lander/README.md
  ow_lander/misc/service_caller.png
  ow_lander/misc/setup_assistant.png
Labels: documentation

#54 Lander Xacro File Tuning
  ow_lander/urdf/lander.xacro
Labels: help wanted

#56 set pid values once for all controllers +
  ow_lander/config/ros_controllers.yaml
Labels: enhancement

#60 Plan using an approximate joint value targets
  ow_lander/scripts/activity_full_digging_traj.py
Labels: bug

#40 Oceanwater 518 switch to using effort controllers joint trajectory controller
  ow/config/default.perspective
  ow_lander/.setup_assistant
  ow_lander/CMakeLists.txt
  ow_lander/README.md
  ow_lander/config/fake_controllers.yaml
  ow_lander/config/joint_limits.yaml
  ow_lander/config/kinematics.yaml
  ow_lander/config/lander.srdf
  ow_lander/config/lander_control.yaml
  ow_lander/config/moveit.rviz
  ow_lander/config/ompl_planning.yaml
  ow_lander/config/ros_controllers.yaml
  ow_lander/launch/fake_moveit_controller_manager.launch.xml
  ow_lander/launch/gazebo.launch
  ow_lander/launch/lander_moveit_controller_manager.launch.xml
  ow_lander/launch/move_group.launch
  ow_lander/launch/moveit_rviz.launch
  ow_lander/launch/ompl_planning_pipeline.launch.xml
  ow_lander/launch/planning.launch
  ow_lander/launch/planning_context.launch
  ow_lander/launch/planning_pipeline.launch.xml
  ow_lander/launch/ros_controllers.launch
  ow_lander/launch/setup_assistant.launch
  ow_lander/launch/spawn.launch
  ow_lander/launch/trajectory_execution.launch.xml
  ow_lander/misc/service_caller.png
  ow_lander/misc/setup_assistant.png
  ow_lander/msg/GuardedMoveResult.msg
  ow_lander/package.xml
  ow_lander/scripts/activity_deliver_sample.py
  ow_lander/scripts/activity_full_digging_traj.py
  ow_lander/scripts/activity_grind.py
  ow_lander/scripts/activity_guarded_move.py
  ow_lander/scripts/ground_detection.py
  ow_lander/scripts/path_planning_commander.py
  ow_lander/scripts/trajectory_async_execution.py
  ow_lander/scripts/trajectory_publisher.py
  ow_lander/scripts/utils.py
  ow_lander/srv/DeliverSample.srv
  ow_lander/srv/DigCircular.srv
  ow_lander/srv/DigLinear.srv
  ow_lander/srv/Grind.srv
  ow_lander/srv/GuardedMove.srv
  ow_lander/srv/Stow.srv
  ow_lander/srv/Unstow.srv
  ow_lander/urdf/lander.xacro
Labels: feature
